# Use the official Microsoft .NET SDK image from the DockerHub
#FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
FROM mcr.microsoft.com/dotnet/aspnet:6.0

# Set the working directory in the Docker container
WORKDIR /src

# Copy csproj and restore as distinct layers
COPY *.csproj ./
COPY LoginProtocol/*.csproj ./LoginProtocol/
RUN dotnet restore

# Copy the rest of the application source code
COPY . .

# Build the application in Release mode
RUN dotnet build -c Release

# Publish the application in Release mode
RUN dotnet publish -c Release -o /app/publish

# Use the official Microsoft .NET Runtime image from the DockerHub
FROM mcr.microsoft.com/dotnet/runtime:6.0

# Set the working directory in the Docker container
WORKDIR /app

# Copy the publish directory from the build image
COPY --from=build /app/publish .

# Set environment variables if any are needed for your app to run
# ENV ConnectionStrings__DefaultConnection="YourConnectionString"

# Specify the entry point of your app
ENTRYPOINT ["dotnet", "Parlo.Docker.dll"]